"""
Static task registry built from workflows/*/tasks_config.py definitions.
Each workflow maps to a dict of tasks with their Celery path, queue, schedule, and default kwargs.

AUTO-GENERATED by frontend/generate_registry.py
Run `python frontend/generate_registry.py` after adding or changing tasks in workflows/*/tasks_config.py.
"""
from typing import TypedDict


class TaskDef(TypedDict):
    key: str
    label: str
    task_path: str
    queue: str
    schedule: str
    kwargs: dict
    description: str
    manual_only: bool


class WorkflowDef(TypedDict):
    label: str
    color: str           # tailwind color name: blue | emerald | violet
    description: str
    tasks: list[TaskDef]


TASK_REGISTRY: dict[str, WorkflowDef] = {

    # ──────────────────────────────────────────────────────────────────────────
    # HUD           Desktop heads-up display — Rainmeter widgets for forex, calendar, budgets, and TCG orders.
    # ──────────────────────────────────────────────────────────────────────────
    'hud': {
        "label":       'HUD',
        "color":       'blue',
        "description": 'Desktop heads-up display — Rainmeter widgets for forex, calendar, budgets, and TCG orders.',
        "tasks": [
            {
                "key":         'show_forex_account',
                "label":       'Show Forex Account',
                "task_path":   'workflows.hud.tasks.hud_forex.show_forex_account',
                "queue":       'hud',
                "schedule":    'Every 15 min (Mon–Fri)',
                "kwargs":      {'cfg_id__oanda': 'OANDA', 'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_tcg_orders',
                "label":       'Show Tcg Orders',
                "task_path":   'workflows.hud.tasks.hud_tcg.show_tcg_orders',
                "queue":       'tcg',
                "schedule":    'Every hour',
                "kwargs":      {'cfg_id__tcg_mp': 'TCG_MP', 'cfg_id__scryfall': 'SCRYFALL', 'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_tcg_orders_no_schedule',
                "label":       'Show Tcg Orders No Schedule',
                "task_path":   'workflows.hud.tasks.hud_tcg.show_tcg_orders',
                "queue":       'adhoc',
                "schedule":    'Every hour',
                "kwargs":      {'cfg_id__tcg_mp': 'TCG_MP', 'cfg_id__scryfall': 'SCRYFALL', 'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'get_desktop_logs',
                "label":       'Get Desktop Logs',
                "task_path":   'workflows.hud.tasks.hud_gpt.get_desktop_logs',
                "queue":       'default',
                "schedule":    'Hourly at :05',
                "kwargs":      {'cfg_id__desktop': 'DESKTOP', 'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'take_screenshots_for_gpt_capture',
                "label":       'Take Screenshots For Gpt Capture',
                "task_path":   'workflows.hud.tasks.hud_gpt.take_screenshots_for_gpt_capture',
                "queue":       'default',
                "schedule":    'Every 10 min',
                "kwargs":      {'cfg_id__desktop': 'DESKTOP'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_calendar_information',
                "label":       'Show Calendar Information',
                "task_path":   'workflows.hud.tasks.hud_calendar.show_calendar_information',
                "queue":       'hud',
                "schedule":    'Every 15 min',
                "kwargs":      {'cfg_id__calendar': 'GOOGLE_APPS', 'cfg_id__elevenlabs': 'ELEVEN_LABS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'get_failed_jobs',
                "label":       'Get Failed Jobs',
                "task_path":   'workflows.hud.tasks.hud_logs.get_failed_jobs',
                "queue":       'hud',
                "schedule":    'Every 15 min',
                "kwargs":      {},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_mouse_bindings',
                "label":       'Show Mouse Bindings',
                "task_path":   'workflows.hud.tasks.hud_utils.show_mouse_bindings',
                "queue":       'hud',
                "schedule":    'Every 15 sec',
                "kwargs":      {'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'build_summary_mouse_bindings',
                "label":       'Build Summary Mouse Bindings',
                "task_path":   'workflows.hud.tasks.hud_utils.build_summary_mouse_bindings',
                "queue":       'default',
                "schedule":    '<crontab: * 1 * * * (m/h/dM/MY/d)>',
                "kwargs":      {'cfg_id__desktop': 'DESKTOP'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_hud_profiles',
                "label":       'Show Hud Profiles',
                "task_path":   'workflows.hud.tasks.hud_utils.show_hud_profiles',
                "queue":       'hud',
                "schedule":    '<crontab: * 00 * * * (m/h/dM/MY/d)>',
                "kwargs":      {},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_ynab_budgets_info',
                "label":       'Show Ynab Budgets Info',
                "task_path":   'workflows.hud.tasks.hud_finance.show_ynab_budgets_info',
                "queue":       'hud',
                "schedule":    '<crontab: * 0,4,8,12,16,20 * * * (m/h/dM/MY/d)>',
                "kwargs":      {'cfg_id__ynab': 'YNAB', 'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'show_ai_helper',
                "label":       'Show Ai Helper',
                "task_path":   'workflows.hud.tasks.hud_utils.show_ai_helper',
                "queue":       'hud',
                "schedule":    '<crontab: * 0 * * * (m/h/dM/MY/d)>',
                "kwargs":      {'cfg_id__n8n': 'N8N', 'cfg_id__eleven': 'ELEVEN_LABS', 'cfg_id__py': 'PYTHON_RUNNER'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'get_schedules',
                "label":       'Get Schedules',
                "task_path":   'workflows.hud.tasks.hud_logs.get_schedules',
                "queue":       'hud',
                "schedule":    '<crontab: * 0,4,8,12,16,20 * * * (m/h/dM/MY/d)>',
                "kwargs":      {'cfg_id__calendar': 'GOOGLE_APPS'},
                "description": '',
                "manual_only": False,
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────────────
    # PURCHASES     MTG card resale pipeline — Scryfall bulk data → listings → price updates → order audit.
    # ──────────────────────────────────────────────────────────────────────────
    'purchases': {
        "label":       'Purchases',
        "color":       'emerald',
        "description": 'MTG card resale pipeline — Scryfall bulk data → listings → price updates → order audit.',
        "tasks": [
            {
                "key":         'download_scryfall_bulk_data',
                "label":       'Download Scryfall Bulk Data',
                "task_path":   'workflows.purchases.tasks.tcg_mp_selling.download_scryfall_bulk_data',
                "queue":       'tcg',
                "schedule":    '1st of month at 2am',
                "kwargs":      {'cfg_id__scryfall': 'SCRYFALL'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'generate_audit_for_tcg_orders',
                "label":       'Generate Audit For Tcg Orders',
                "task_path":   'workflows.purchases.tasks.tcg_mp_selling.generate_audit_for_tcg_orders',
                "queue":       'tcg',
                "schedule":    'Every 4 hours',
                "kwargs":      {'cfg_id__tcg_mp': 'TCG_MP'},
                "description": '',
                "manual_only": False,
            },
        ],
    },

    # ──────────────────────────────────────────────────────────────────────────
    # DESKTOP       Windows desktop automation — git pulls, window management, file sync, and activity capture.
    # ──────────────────────────────────────────────────────────────────────────
    'desktop': {
        "label":       'Desktop',
        "color":       'violet',
        "description": 'Windows desktop automation — git pulls, window management, file sync, and activity capture.',
        "tasks": [
            {
                "key":         'git_pull_on_paths',
                "label":       'Git Pull On Paths',
                "task_path":   'workflows.desktop.tasks.commands.git_pull_on_paths',
                "queue":       'default',
                "schedule":    'Every 10 min',
                "kwargs":      {},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'set_desktop_hud_to_back',
                "label":       'Set Desktop Hud To Back',
                "task_path":   'workflows.desktop.tasks.commands.set_desktop_hud_to_back',
                "queue":       'default',
                "schedule":    'Every 30 min',
                "kwargs":      {},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'copy_files_targeted',
                "label":       'Copy Files Targeted',
                "task_path":   'workflows.desktop.tasks.commands.copy_files_targeted',
                "queue":       'default',
                "schedule":    'Every 30 min',
                "kwargs":      {'cfg_id__desktop_jobs': 'DESKTOP'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'run_n8n_sequence',
                "label":       'Run N8N Sequence',
                "task_path":   'workflows.desktop.tasks.commands.run_n8n_sequence',
                "queue":       'default',
                "schedule":    'Daily at midnight',
                "kwargs":      {},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'run_capture_logging',
                "label":       'Run Capture Logging',
                "task_path":   'workflows.desktop.tasks.capture.run_capture_logging',
                "queue":       'default',
                "schedule":    'Every 15 min',
                "kwargs":      {'cfg_id__desktop_utils': 'DESKTOP'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'generate_daily_desktop_summary',
                "label":       'Generate Daily Desktop Summary',
                "task_path":   'workflows.desktop.tasks.capture.generate_daily_desktop_summary',
                "queue":       'default',
                "schedule":    'Daily at 23:55',
                "kwargs":      {'hud_item_name': 'DESKTOP LOGS', 'logs_output_path': 'C:/Users/brian/GIT/harqis-work/logs/daily'},
                "description": '',
                "manual_only": False,
            },
            {
                "key":         'generate_weekly_desktop_summary',
                "label":       'Generate Weekly Desktop Summary',
                "task_path":   'workflows.desktop.tasks.capture.generate_weekly_desktop_summary',
                "queue":       'default',
                "schedule":    'Sun at 23:58',
                "kwargs":      {'logs_daily_path': 'C:/Users/brian/GIT/harqis-work/logs/daily', 'logs_output_path': 'C:/Users/brian/GIT/harqis-work/logs/weekly'},
                "description": '',
                "manual_only": False,
            },
        ],
    },
}
