version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: '%(asctime)s - %(process)d - %(threadName)s - %(levelname)s - %(name)s - %(module)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debugfile:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: app-debug.log
    mode: a
    encoding: utf-8

loggers:
  harqis:
    level: INFO
    handlers: [console]
    propagate: false

  debug:
    level: DEBUG
    handlers: [console, debugfile]
    propagate: false

root:
  level: INFO
  handlers: [console]