"""
workflows/testing/tasks/test_farm.py

BDD "test case farm" — chains the Jira board context used by
``workflows/hud/tasks/hud_jira.show_jira_board`` into a Gherkin generation
prompt sent to the Anthropic API and renders a single living markdown file at
``logs/BDD-TEST-FARM.md``.

Flow (RPA, AI-in-the-loop via the Anthropic API):
  1. Fetch the active-sprint Bug/Story tickets from the same Jira Software board
     the HUD reads (statuses: In Review / In Progress / Ready / In Analysis),
     reusing ``ApiServiceJiraBoards.get_board_issues`` + the sprint filter.
  2. For each ticket, fingerprint the tracked Jira fields + description. If the
     fingerprint matches the sidecar state (``logs/.bdd-test-farm.state.json``)
     the previously generated scenarios are reused; otherwise (new or changed
     ticket) scenarios are regenerated by sending a single, self-contained
     Gherkin-generation prompt to the Anthropic API via
     ``BaseApiServiceAnthropic.send_message`` (Sonnet, bounded ``max_tokens``).
  3. Render ``logs/BDD-TEST-FARM.md``: a navigable summary table at the top
     (active tickets only, sorted by issue type then status) plus one section
     per ticket (tracked fields + the generated Gherkin). Tickets that drop out
     of the active focus columns (closed / moved) keep their scenarios under a
     "Retained" group but are removed from the summary table.

Why the API and not the local ``claude`` CLI: this task runs unattended on a
schedule. The Claude Max subscription that backs the ``claude`` CLI is licensed
for interactive Claude Code use, so automated/headless runs must bill the
Anthropic API instead (``ANTHROPIC_API_KEY``). The Gherkin conventions that
the ``/generate-gherkin-scenarios`` skill encodes are inlined into the system
prompt here so the API call is fully self-contained (no skill/tool runtime).
Generation is intentionally token-frugal: a static system prompt carries the
conventions, the per-ticket user message carries only the ticket fields, and
output is capped via ``max_tokens``.

References:
- workflows/hud/tasks/hud_jira.py — board fetch + status/type context (mirrored).
- workflows/finance/tasks/parse_transaction.py — AI-in-the-loop task pattern.
- apps/antropic/references/web/base_api_service.py — the API client used here.
- .claude/skills/generate-gherkin-scenarios/SKILL.md — source of the conventions
  inlined into the system prompt below.
"""

import re
import json
import time
import hashlib
from datetime import datetime
from pathlib import Path
from typing import List

from core.apps.sprout.app.celery import SPROUT
from core.apps.es_logging.app.elasticsearch import log_result
from core.utilities.logging.custom_logger import create_logger

from apps.apps_config import CONFIG_MANAGER
from apps.jira.references.web.api.boards import ApiServiceJiraBoards
from apps.jira.config import APP_NAME as APP_NAME_JIRA
from apps.antropic.config import get_config as get_anthropic_config, APP_NAME as APP_NAME_ANTHROPIC
from apps.antropic.references.web.base_api_service import BaseApiServiceAnthropic

from workflows.testing.prompts import load_prompt

_log = create_logger("testing.test_farm")

# ── Paths ───────────────────────────────────────────────────────────────────
# __file__ = repo/workflows/testing/tasks/test_farm.py → parents[3] = repo root.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_LOGS_DIR = _REPO_ROOT / "logs"
_FARM_MD = _LOGS_DIR / "BDD-TEST-FARM.md"
_STATE_FILE = _LOGS_DIR / ".bdd-test-farm.state.json"

# ── Jira context (mirrors workflows/hud/tasks/hud_jira.py) ────────────────────
# Same board + sprint scope the HUD reads. Statuses kept in display order.
DEFAULT_STATUSES: List[str] = ["In Review", "In Progress", "Ready", "In Analysis"]
# Bugs and stories only — the HUD also surfaces Task; the farm intentionally does not.
_INCLUDED_ISSUE_TYPES: tuple = ("Bug", "Story")
# Tracked fields rendered + fingerprinted per ticket (mirrors hud_jira._JIRA_FIELDS).
_TRACKED_FIELDS: List[str] = ["summary", "assignee", "priority", "fixVersions", "issuetype", "status"]
# What we actually request from Jira: tracked fields + description (ACs live here)
# + updated (cheap, handy for logs).
_FETCH_FIELDS: List[str] = _TRACKED_FIELDS + ["description", "updated"]
# Scope every fetch to the active sprint, exactly like the HUD widget.
_SPRINT_FILTER_JQL: str = "sprint in openSprints()"
_MAX_BOARD_ISSUES: int = 200

# Anthropic model id for generation. Sonnet is the cost/quality sweet spot for a
# scheduled batch; pass model='claude-opus-4-8' in kwargs for deeper one-off runs.
_DEFAULT_MODEL: str = "claude-sonnet-4-6"
# apps_config.yaml section key for the Anthropic service (API-key auth).
_DEFAULT_ANTHROPIC_CFG_ID: str = APP_NAME_ANTHROPIC
# Output cap per ticket. A full feature file + AC↔scenario mapping + tally for a
# multi-AC ticket fits comfortably under this; bounding it keeps token spend
# (and cost) predictable per run.
_DEFAULT_MAX_TOKENS: int = 4000
# Rate limiting: seconds to pause between consecutive API generations. Tickets
# are processed strictly one at a time; this gap keeps the API rolling-window
# limits comfortable on a busy board. Only applied after a ticket that actually
# called the API (cache reuses don't wait), and never after the last one.
_DEFAULT_INTER_TICKET_DELAY: int = 5


# ── Jira field extraction ─────────────────────────────────────────────────────

def _coerce_text(value) -> str:
    """Render a Jira description as plain text.

    Server/DC (this deployment, ``/rest/api/2/``) returns the description as a
    plain string; Jira Cloud returns Atlassian Document Format (ADF) as nested
    dicts. Handle both so the task is portable: pull every ``text`` node out of
    an ADF tree, otherwise return the string as-is.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    parts: List[str] = []

    def _walk(node):
        if isinstance(node, dict):
            if node.get("type") == "text" and isinstance(node.get("text"), str):
                parts.append(node["text"])
            for v in node.values():
                _walk(v)
        elif isinstance(node, list):
            for v in node:
                _walk(v)

    _walk(value)
    return "\n".join(parts)


def _extract_fields(issue: dict) -> dict:
    """Flatten a Jira issue into the fields the farm tracks and renders."""
    f = (issue or {}).get("fields", {}) or {}
    fix_versions = [v.get("name") for v in (f.get("fixVersions") or []) if v.get("name")]
    return {
        "key": (issue or {}).get("key") or "",
        "summary": f.get("summary") or "",
        "assignee": ((f.get("assignee") or {}).get("displayName")) or "Unassigned",
        "priority": ((f.get("priority") or {}).get("name")) or "-",
        "issuetype": ((f.get("issuetype") or {}).get("name")) or "-",
        "status": ((f.get("status") or {}).get("name")) or "-",
        "fix_versions": fix_versions,
        "description": _coerce_text(f.get("description")),
        "updated": f.get("updated") or "",
    }


def _resolve_column_status_ids(api_boards, board_id: int, columns: List[str]) -> dict:
    """Map each requested board column → set of underlying Jira status IDs.

    Mirrors ``workflows/hud/tasks/hud_jira._resolve_column_status_ids``: a board
    column named "In Review" can map to underlying statuses called "Code Review",
    "QA Review", etc., so the four focus *columns* (In Review / In Progress /
    Ready / In Analysis) are NOT real status names and can't be matched by name.
    Reads ``/board/{id}/configuration`` and keeps only the requested columns.

    Returns ``{column_name: set(status_ids)}``; an empty set means "fall back to
    status-name matching for this column" (also what happens if the config call
    fails). Always keyed by every requested column.
    """
    requested_lc = {c.strip().lower(): c for c in columns}
    out: dict = {c: set() for c in columns}
    try:
        config = api_boards.get_configuration(board_id) or {}
    except Exception as e:
        _log.warning("test_farm: board configuration unavailable — "
                     "falling back to status-name matching: %s", e)
        return out
    for col in (config.get("columnConfig") or {}).get("columns", []) or []:
        canonical = requested_lc.get((col.get("name") or "").strip().lower())
        if canonical is None:
            continue
        out[canonical] = {str(s.get("id")) for s in (col.get("statuses") or []) if s.get("id")}
    return out


def _issue_in_columns(issue: dict, columns: List[str], column_status_ids: dict) -> bool:
    """True if the issue's status belongs to any of the requested columns.

    By status ID when the column's id-set is populated (the accurate path);
    otherwise by case-insensitive status-name == column-name fallback.
    """
    status_field = ((issue or {}).get("fields") or {}).get("status") or {}
    status_id = str(status_field.get("id")) if status_field.get("id") else None
    status_name = (status_field.get("name") or "").strip().lower()
    for col in columns:
        ids = column_status_ids.get(col) or set()
        if ids:
            if status_id and status_id in ids:
                return True
        elif status_name and status_name == col.strip().lower():
            return True
    return False


def _fingerprint(fields: dict) -> str:
    """Stable hash over the fields whose change should trigger a regeneration."""
    payload = json.dumps(
        {k: fields[k] for k in
         ("summary", "assignee", "priority", "issuetype", "status", "fix_versions", "description")},
        sort_keys=True, ensure_ascii=False,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


# ── Sidecar state ───────────────────────────────────────────────────────────

def _load_state() -> dict:
    if _STATE_FILE.exists():
        try:
            return json.loads(_STATE_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as e:
            _log.warning("test_farm: state file unreadable (%s) — starting fresh", e)
    return {}


def _save_state(state: dict) -> None:
    _LOGS_DIR.mkdir(parents=True, exist_ok=True)
    _STATE_FILE.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")


# ── Anthropic API (Gherkin generation) ───────────────────────────────────────

# Inlined Gherkin conventions — the durable instruction set the
# /generate-gherkin-scenarios skill encodes, condensed for an unattended API
# call (no tools, no clarifying questions). Kept static so it can be reused as
# the system prompt across every ticket in a run (the per-ticket user message
# carries only the ticket fields), which keeps token spend frugal.
_SYSTEM_PROMPT: str = """\
You are the Gherkin Scenario Generator for the harqis-work test farm, running \
UNATTENDED on a schedule. Turn the Acceptance-Criteria spec in the user message \
into a clean, idiomatic Gherkin .feature file following cucumber.io best practice.

Operating rules (headless):
- Do NOT ask clarifying questions and do NOT use any tools. Everything you need \
is in the user message. Where you would normally ask, choose the most reasonable \
interpretation and list residual ambiguity under a final "## Open questions" heading.
- Generate scenarios for ALL acceptance criteria you can identify. Skip \
struck-through / deprecated ACs (e.g. -…AC text…-) and note the skip in the \
feature-file header comment.

Feature-file conventions:
- Header comment with the ticket key + summary, the AC scope, and a short tag legend.
- Tag legend: @AC<n> (AC mapping), @functional, @integration, @negative, @edge, @smoke.
- Tag order is AC first, then type, then @smoke: e.g. "@AC2 @functional @smoke".
- Per AC, aim for at least: 1x @functional @smoke (happy path), 1x @negative \
(bypass / invalid input / permission denied), and 1x @integration OR @edge when \
the AC has system-spanning side-effects or unusual inputs. Don't pad trivial ACs.
- Declarative, not imperative: describe business behaviour, not UI choreography.
- One behaviour per Scenario (one When/Then block); shared state in a short \
Background (state setup only, no When); Scenario Outline only for true data variation.
- No "Validate that…/Check if…/Verify that…", no assertion-language leak \
("returns 200", "should equal"), no implementation/response-body leakage. Quote \
literal user-facing strings.

Output EXACTLY this, in order, and nothing else (no preamble, no closing chatter):
1. A single fenced ```gherkin code block containing the .feature file.
2. The "AC <-> scenario" coverage mapping table.
3. The type-coverage tally line (N x @functional, M x @integration, ...).
4. An optional "## Open questions" section only if ambiguity remains.
"""


def _build_anthropic_service(cfg_id: str, model: str,
                             max_tokens: int) -> BaseApiServiceAnthropic:
    """Construct the Anthropic API service once per run.

    Auth resolves via ``apps.antropic.provider`` — for a scheduled/unattended
    run that means ``ANTHROPIC_API_KEY`` (the Max subscription is interactive-
    only and is never auto-selected when an API key is present). ``model`` and
    ``max_tokens`` are pinned on the instance so every per-ticket call inherits
    the frugal defaults without re-passing them.
    """
    svc = BaseApiServiceAnthropic(get_anthropic_config(cfg_id))
    svc.model = model
    svc.max_tokens = max_tokens
    return svc


def _response_text(resp) -> str:
    """Flatten an Anthropic Messages response into plain text."""
    parts: List[str] = []
    for block in (getattr(resp, "content", None) or []):
        text = getattr(block, "text", None)
        if text:
            parts.append(text)
    return "\n".join(parts).strip()


def _generate_gherkin_via_api(fields: dict, *, service: BaseApiServiceAnthropic,
                              model: str, max_tokens: int) -> str:
    """Send one self-contained generation prompt to the API; return the text.

    The static conventions live in ``_SYSTEM_PROMPT``; the per-ticket user
    message carries only the ticket fields, so the variable token cost scales
    with the ticket, not the instruction set.
    """
    user_prompt = load_prompt("test_farm").format(
        key=fields["key"],
        summary=fields["summary"],
        issuetype=fields["issuetype"],
        priority=fields["priority"],
        status=fields["status"],
        fix_versions=", ".join(fields["fix_versions"]) or "-",
        description=fields["description"] or "(no description provided in the ticket)",
    )

    _log.info("test_farm: generating scenarios for %s via Anthropic API (model=%s)",
              fields["key"], model)
    resp = service.send_message(
        prompt=user_prompt,
        model=model,
        max_tokens=max_tokens,
        system=_SYSTEM_PROMPT,
    )
    out = _response_text(resp)
    if not out:
        raise RuntimeError(f"Anthropic API returned empty output for {fields['key']}")
    return out


# ── Markdown rendering ──────────────────────────────────────────────────────

def _slug(key: str) -> str:
    """GitHub-stable anchor slug for a ticket key (e.g. 'ICON-42' → 'icon-42')."""
    return re.sub(r"[^a-z0-9]+", "-", (key or "").lower()).strip("-")


def _cell(text: str) -> str:
    """Escape a value for a single markdown table cell."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _ticket_url(domain: str, key: str) -> str:
    """Browse URL for a Jira ticket, or '' when the domain isn't configured.

    Mirrors the link convention in ``workflows/hud/tasks/hud_jira`` (which reads
    ``cfg__jira.app_data['domain']``): a ticket lives at
    ``https://{domain}/browse/{KEY}``.
    """
    if not domain or not key:
        return ""
    return f"https://{domain.strip('/')}/browse/{key}"


# Summary ordering: issue type (Story → Bug), then status (Quality Review →
# In Progress → New → anything else), then key for a stable tie-break.
_ISSUETYPE_ORDER: tuple = ("Story", "Bug")
_STATUS_ORDER: tuple = ("Quality Review", "In Progress", "New")


def _sort_key(entry: dict) -> tuple:
    """Sort rank for an entry: (issue-type, status, key)."""
    it = entry.get("issuetype") or ""
    st = entry.get("status") or ""
    it_rank = _ISSUETYPE_ORDER.index(it) if it in _ISSUETYPE_ORDER else len(_ISSUETYPE_ORDER)
    st_rank = _STATUS_ORDER.index(st) if st in _STATUS_ORDER else len(_STATUS_ORDER)
    return (it_rank, st_rank, entry.get("key") or "")


def _render_section(e: dict, *, retained: bool = False) -> List[str]:
    """Render one ticket section: anchor + heading + field table + scenarios."""
    out: List[str] = []
    out.append(f'<a id="{_slug(e["key"])}"></a>')
    out.append(f"## {e['key']} — {e['summary']}" + ("  _(retained)_" if retained else ""))
    out.append("")
    out.append("| Field | Value |")
    out.append("|-------|-------|")
    out.append(f"| Ticket Id | {e['key']} |")
    out.append(f"| Name | {_cell(e['summary'])} |")
    out.append(f"| Priority | {e.get('priority', '-')} |")
    out.append(f"| Assignee | {_cell(e.get('assignee', '-'))} |")
    out.append(f"| Issue Type | {e['issuetype']} |")
    out.append(f"| Status | {e['status']}" + (" (last known)" if retained else "") + " |")
    out.append(f"| Fix Version(s) | {_cell(', '.join(e.get('fix_versions') or []) or '-')} |")
    out.append(f"| Last generated | {e.get('generated_at', '—')} |")
    out.append("")
    out.append(e["gherkin"])
    out.append("")
    out.append("---")
    out.append("")
    return out


def _render_md(active: List[dict], retained: List[dict], *,
               board_id, statuses, generated_at: str, jira_domain: str = "") -> str:
    """Render the living document: header + summary nav table + sections.

    The summary table lists ACTIVE tickets only (sorted by issue type then
    status). Sections cover active tickets in the same order, followed by a
    "Retained" group — previously generated tickets no longer in the active
    focus columns (e.g. closed/moved), kept for reference but excluded from
    the summary.
    """
    active_sorted = sorted(active, key=_sort_key)
    retained_sorted = sorted(retained, key=_sort_key)

    out: List[str] = []
    out.append("# BDD Test Case Farm")
    out.append("")
    out.append(f"_Living document — auto-generated by `workflows/testing/tasks/test_farm.py`. "
               f"Last run: {generated_at}._")
    out.append("")
    src = (f"Source: Jira board `{board_id}` · active sprint · "
           f"statuses {list(statuses)} · types {list(_INCLUDED_ISSUE_TYPES)} · "
           f"{len(active_sorted)} active ticket(s)")
    if retained_sorted:
        src += f" · {len(retained_sorted)} retained"
    out.append(src + ".")
    out.append("")

    # ── Summary nav table — ACTIVE only, sorted by issue type then status.
    #    Fields per spec: Summary, FixVersion, Issue Type, Status, section link,
    #    plus a "Web" link straight to the live Jira ticket.
    out.append("## Summary")
    out.append("")
    out.append("| Summary | FixVersion | Issue Type | Status | Tests | Web |")
    out.append("|---------|------------|------------|--------|-------|-----|")
    for e in active_sorted:
        fv = ", ".join(e["fix_versions"]) or "-"
        url = _ticket_url(jira_domain, e["key"])
        web = f"[Web]({url})" if url else "-"
        out.append(f"| {_cell(e['summary'])} | {_cell(fv)} | {e['issuetype']} "
                   f"| {e['status']} | [{e['key']}](#{_slug(e['key'])}) | {web} |")
    out.append("")
    out.append("---")
    out.append("")

    # ── Active sections (same order as the summary) ───────────────────────────
    for e in active_sorted:
        out.extend(_render_section(e))

    # ── Retained sections — kept for history, not in the summary above ────────
    if retained_sorted:
        out.append("# Retained — no longer in the active focus columns")
        out.append("")
        out.append("_Scenarios kept for reference (closed / moved tickets). "
                   "Not listed in the summary; status shown is last known._")
        out.append("")
        for e in retained_sorted:
            out.extend(_render_section(e, retained=True))

    return "\n".join(out) + "\n"


# ── Task ──────────────────────────────────────────────────────────────────────

@log_result()
@SPROUT.task()
def run_test_farm(board_id: int, **kwargs):
    """Generate / refresh BDD Gherkin scenarios for active-sprint Bug/Story tickets.

    Tickets are processed strictly one at a time: take the next ticket's data,
    send a self-contained Gherkin-generation prompt to the Anthropic API,
    append the result to the living document, pause (rate limit), repeat. The
    whole markdown file is rewritten after every ticket so the top summary
    table stays in sync and an interrupted run still leaves every completed
    ticket on disk.

    Args:
        board_id: Jira Software board id (`rapidView=<id>` in the board URL) —
                  the same board workflows/hud/tasks/hud_jira reads.

    Kwargs:
        cfg_id__jira:        Config key for Jira (default 'JIRA').
        cfg_id__anthropic:   Config key for the Anthropic API service
                             (default 'ANTHROPIC'; API-key auth).
        statuses:            Status names to include (default DEFAULT_STATUSES).
        model:               Anthropic model id (default 'claude-sonnet-4-6').
        max_tokens:          Output cap per ticket (default 4000).
        inter_ticket_delay:  Seconds to pause between consecutive API
                             generations, for rate limiting (default 5). Skipped
                             on cache reuses and after the final ticket.
        max_results:         Board fetch cap (default 200).
        limit:               Max NEW generations this run (default None = no cap).
                             Deferred tickets show a "pending" placeholder and
                             regenerate on a later run — lets the initial backlog
                             spread across several weekly runs / bounds API spend.
        force:               If True, regenerate every ticket, ignoring the cache.

    Returns:
        Summary string: detected / generated / reused / failed counts + md path.
    """
    cfg_id__jira = kwargs.get("cfg_id__jira", APP_NAME_JIRA)
    cfg_id__anthropic = kwargs.get("cfg_id__anthropic", _DEFAULT_ANTHROPIC_CFG_ID)
    statuses = kwargs.get("statuses") or DEFAULT_STATUSES
    model = kwargs.get("model", _DEFAULT_MODEL)
    max_tokens = int(kwargs.get("max_tokens", _DEFAULT_MAX_TOKENS))
    inter_ticket_delay = int(kwargs.get("inter_ticket_delay", _DEFAULT_INTER_TICKET_DELAY))
    max_results = int(kwargs.get("max_results", _MAX_BOARD_ISSUES))
    force = bool(kwargs.get("force", False))
    _limit = kwargs.get("limit")
    limit = int(_limit) if _limit is not None else None  # max NEW generations this run

    # Build the Anthropic service once and reuse it for every ticket this run.
    anthropic_svc = _build_anthropic_service(cfg_id__anthropic, model, max_tokens)

    cfg__jira = CONFIG_MANAGER.get(cfg_id__jira)
    api_boards = ApiServiceJiraBoards(cfg__jira)
    # Jira domain for per-ticket "Web" links in the summary table (same source
    # the HUD reads — apps_config.yaml::JIRA.app_data.domain). Empty is fine:
    # the renderer falls back to "-" when it can't build a browse URL.
    jira_domain = (getattr(cfg__jira, "app_data", None) or {}).get("domain") or ""

    # Reuse the HUD's sprint scope; filter issue type server-side (Bug/Story
    # are real type names). Status is filtered client-side by *column membership*
    # because the focus statuses are board column names, not status names.
    type_clause = ", ".join(_INCLUDED_ISSUE_TYPES)
    jql = f'{_SPRINT_FILTER_JQL} AND issuetype in ({type_clause}) ORDER BY updated DESC'

    _log.info("test_farm: fetching board %s — jql: %s", board_id, jql)
    response = api_boards.get_board_issues(
        board_id=board_id, jql=jql, fields=_FETCH_FIELDS, max_results=max_results,
    )
    issues = (response or {}).get("issues", []) or []

    # Bucket by board column (In Review / In Progress / Ready / In Analysis) the
    # same way hud_jira does — match underlying status IDs, not column labels.
    column_status_ids = _resolve_column_status_ids(api_boards, board_id, statuses)
    issues = [i for i in issues if _issue_in_columns(i, statuses, column_status_ids)]
    _log.info("test_farm: %d Bug/Story ticket(s) in focus columns on board %s",
              len(issues), board_id)

    state = _load_state()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    candidates = [f for f in (_extract_fields(i) for i in issues) if f["key"]]
    total = len(candidates)
    generated = reused = failed = deferred = 0

    # Retained tickets: previously generated but no longer in the active focus
    # columns (closed / moved / out of sprint). Their scenarios are kept in the
    # document (rendered after the active ones) but excluded from the summary.
    # State is never pruned, so they persist across runs.
    candidate_keys = {f["key"] for f in candidates}
    retained: List[dict] = []
    for k, s in state.items():
        if k in candidate_keys:
            continue
        flds = s.get("fields")
        if not (flds and s.get("gherkin")):
            continue
        retained.append({"key": k, **flds, "gherkin": s["gherkin"],
                         "generated_at": s.get("generated_at", "—")})

    def _flush() -> None:
        """Re-render the living document from the current entry state."""
        md = _render_md(entries, retained, board_id=board_id, statuses=statuses,
                        generated_at=now, jira_domain=jira_domain)
        _LOGS_DIR.mkdir(parents=True, exist_ok=True)
        _FARM_MD.write_text(md, encoding="utf-8")

    # Pre-seed every detected ticket with a placeholder so the document shows the
    # full summary table + all sections immediately; each section is then filled
    # in as its ticket is processed (the file is never blank during a slow run).
    entries: List[dict] = [
        {**f, "gherkin": "> _Queued — scenarios will appear here once generated._",
         "generated_at": "—"}
        for f in candidates
    ]
    _flush()

    # ── One ticket at a time: take the next ticket's data → call the API →
    #    append to the document → pause (rate limit) → repeat. ──────────────────
    for idx, fields in enumerate(candidates):
        key = fields["key"]
        fp = _fingerprint(fields)
        prior = state.get(key) or {}
        unchanged = (not force) and prior.get("fingerprint") == fp and prior.get("gherkin")
        called_api = False

        if unchanged:
            gherkin = prior["gherkin"]
            gen_at = prior.get("generated_at", now)
            reused += 1
            _log.info("test_farm: [%d/%d] %s unchanged — reusing scenarios", idx + 1, total, key)
        elif limit is not None and generated >= limit:
            # Per-run generation budget reached: defer this ticket. Show prior
            # scenarios if we have them, else a placeholder. Don't touch state,
            # so it regenerates on a later run.
            deferred += 1
            gherkin = prior.get("gherkin") or \
                "> _Pending — deferred to a later run (per-run generation limit reached)._"
            gen_at = prior.get("generated_at", "—")
            _log.info("test_farm: [%d/%d] %s — deferred (limit %d reached)", idx + 1, total, key, limit)
        else:
            called_api = True
            _log.info("test_farm: [%d/%d] %s — generating scenarios", idx + 1, total, key)
            try:
                gherkin = _generate_gherkin_via_api(
                    fields, service=anthropic_svc, model=model, max_tokens=max_tokens,
                )
            except Exception as e:
                # Don't fail the whole batch on one ticket. Keep prior scenarios
                # if we have them (and leave the old fingerprint so it retries
                # next run); otherwise drop a visible placeholder.
                _log.error("test_farm: generation failed for %s: %s", key, e)
                failed += 1
                if prior.get("gherkin"):
                    gherkin = prior["gherkin"]
                    gen_at = prior.get("generated_at", now)
                else:
                    gherkin = f"> _Scenario generation failed on {now}: {e}_"
                    gen_at = now
            else:
                gen_at = now
                generated += 1
                state[key] = {
                    "fingerprint": fp,
                    "generated_at": gen_at,
                    "fields": {k: fields[k] for k in
                               ("summary", "assignee", "priority", "issuetype", "status", "fix_versions")},
                    "gherkin": gherkin,
                }
                _save_state(state)   # persist the cache as we go — resumable

        entries[idx] = {**fields, "gherkin": gherkin, "generated_at": gen_at}
        _flush()                     # update this ticket's section in the document now

        # Rate limit: pause only after a real API call, never after the last.
        if called_api and idx < total - 1 and inter_ticket_delay > 0:
            _log.info("test_farm: rate-limit pause %ds before next ticket", inter_ticket_delay)
            time.sleep(inter_ticket_delay)

    _save_state(state)
    summary = (f"BDD farm: {total} ticket(s) — {generated} generated, "
               f"{reused} reused, {deferred} deferred, {failed} failed → {_FARM_MD}")
    _log.info(summary)
    return summary
