"""
workflows/testing/tasks/test_farm.py

BDD "test case farm" — chains the Jira board context used by
``workflows/hud/tasks/hud_jira.show_jira_board`` into the
``/generate-gherkin-scenarios`` Claude Code skill and renders a single living
markdown file at ``logs/BDD-TEST-FARM.md``.

Flow (RPA, AI-in-the-loop via the local Claude Code CLI):
  1. Fetch the active-sprint Bug/Story tickets from the same Jira Software board
     the HUD reads (statuses: In Review / In Progress / Ready / In Analysis),
     reusing ``ApiServiceJiraBoards.get_board_issues`` + the sprint filter.
  2. For each ticket, fingerprint the tracked Jira fields + description. If the
     fingerprint matches the sidecar state (``logs/.bdd-test-farm.state.json``)
     the previously generated scenarios are reused; otherwise (new or changed
     ticket) scenarios are regenerated by invoking the real
     ``/generate-gherkin-scenarios`` skill through the locally-installed,
     Max-subscription-authenticated ``claude`` CLI in headless mode
     (``claude -p``) with a thinking model.
  3. Render ``logs/BDD-TEST-FARM.md``: a navigable summary table at the top plus
     one section per ticket (tracked fields + the generated Gherkin).

Why the CLI and not the Anthropic API: running the actual skill keeps a single
source of truth for the Gherkin conventions, and routing through the local
Claude Code login draws on the user's Max subscription (no per-token API cost)
while allowing extended "thinking". The ``peon`` queue is pinned to this Windows
host (``windows-work-all``), which is where ``claude`` is installed + logged in.

References:
- workflows/hud/tasks/hud_jira.py — board fetch + status/type context (mirrored).
- workflows/finance/tasks/parse_transaction.py — AI-in-the-loop task pattern.
- .claude/skills/generate-gherkin-scenarios/SKILL.md — the skill invoked headless.
"""

import os
import re
import json
import time
import shutil
import hashlib
import subprocess
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from core.apps.sprout.app.celery import SPROUT
from core.apps.es_logging.app.elasticsearch import log_result
from core.utilities.logging.custom_logger import create_logger

from apps.apps_config import CONFIG_MANAGER
from apps.jira.references.web.api.boards import ApiServiceJiraBoards
from apps.jira.config import APP_NAME as APP_NAME_JIRA

from workflows.testing.prompts import load_prompt

_log = create_logger("testing.test_farm")

# ── Paths ───────────────────────────────────────────────────────────────────
# __file__ = repo/workflows/testing/tasks/test_farm.py → parents[3] = repo root.
_REPO_ROOT = Path(__file__).resolve().parents[3]
_LOGS_DIR = _REPO_ROOT / "logs"
_FARM_MD = _LOGS_DIR / "BDD-TEST-FARM.md"
_STATE_FILE = _LOGS_DIR / ".bdd-test-farm.state.json"

# ── Jira context (mirrors workflows/hud/tasks/hud_jira.py) ────────────────────
# Same board + sprint scope the HUD reads. Statuses kept in display order.
DEFAULT_STATUSES: List[str] = ["In Review", "In Progress", "Ready", "In Analysis"]
# Bugs and stories only — the HUD also surfaces Task; the farm intentionally does not.
_INCLUDED_ISSUE_TYPES: tuple = ("Bug", "Story")
# Tracked fields rendered + fingerprinted per ticket (mirrors hud_jira._JIRA_FIELDS).
_TRACKED_FIELDS: List[str] = ["summary", "assignee", "priority", "fixVersions", "issuetype", "status"]
# What we actually request from Jira: tracked fields + description (ACs live here)
# + updated (cheap, handy for logs).
_FETCH_FIELDS: List[str] = _TRACKED_FIELDS + ["description", "updated"]
# Scope every fetch to the active sprint, exactly like the HUD widget.
_SPRINT_FILTER_JQL: str = "sprint in openSprints()"
_MAX_BOARD_ISSUES: int = 200

# ``claude --model`` alias. Both sonnet and opus support extended thinking on the
# Max subscription; sonnet has the more generous limits for a daily batch.
_DEFAULT_CLAUDE_MODEL: str = "sonnet"
# Per-ticket headless generation timeout (seconds). A thinking run on a meaty
# ticket can take a few minutes.
_DEFAULT_PER_TICKET_TIMEOUT: int = 420
# Rate limiting: seconds to pause between consecutive Claude generations. Tickets
# are processed strictly one at a time; this gap keeps the Max-subscription
# rolling-window limits comfortable on a busy board. Only applied after a ticket
# that actually called Claude (cache reuses don't wait), and never after the
# last one.
_DEFAULT_INTER_TICKET_DELAY: int = 5


# ── Jira field extraction ─────────────────────────────────────────────────────

def _coerce_text(value) -> str:
    """Render a Jira description as plain text.

    Server/DC (this deployment, ``/rest/api/2/``) returns the description as a
    plain string; Jira Cloud returns Atlassian Document Format (ADF) as nested
    dicts. Handle both so the task is portable: pull every ``text`` node out of
    an ADF tree, otherwise return the string as-is.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    parts: List[str] = []

    def _walk(node):
        if isinstance(node, dict):
            if node.get("type") == "text" and isinstance(node.get("text"), str):
                parts.append(node["text"])
            for v in node.values():
                _walk(v)
        elif isinstance(node, list):
            for v in node:
                _walk(v)

    _walk(value)
    return "\n".join(parts)


def _extract_fields(issue: dict) -> dict:
    """Flatten a Jira issue into the fields the farm tracks and renders."""
    f = (issue or {}).get("fields", {}) or {}
    fix_versions = [v.get("name") for v in (f.get("fixVersions") or []) if v.get("name")]
    return {
        "key": (issue or {}).get("key") or "",
        "summary": f.get("summary") or "",
        "assignee": ((f.get("assignee") or {}).get("displayName")) or "Unassigned",
        "priority": ((f.get("priority") or {}).get("name")) or "-",
        "issuetype": ((f.get("issuetype") or {}).get("name")) or "-",
        "status": ((f.get("status") or {}).get("name")) or "-",
        "fix_versions": fix_versions,
        "description": _coerce_text(f.get("description")),
        "updated": f.get("updated") or "",
    }


def _resolve_column_status_ids(api_boards, board_id: int, columns: List[str]) -> dict:
    """Map each requested board column → set of underlying Jira status IDs.

    Mirrors ``workflows/hud/tasks/hud_jira._resolve_column_status_ids``: a board
    column named "In Review" can map to underlying statuses called "Code Review",
    "QA Review", etc., so the four focus *columns* (In Review / In Progress /
    Ready / In Analysis) are NOT real status names and can't be matched by name.
    Reads ``/board/{id}/configuration`` and keeps only the requested columns.

    Returns ``{column_name: set(status_ids)}``; an empty set means "fall back to
    status-name matching for this column" (also what happens if the config call
    fails). Always keyed by every requested column.
    """
    requested_lc = {c.strip().lower(): c for c in columns}
    out: dict = {c: set() for c in columns}
    try:
        config = api_boards.get_configuration(board_id) or {}
    except Exception as e:
        _log.warning("test_farm: board configuration unavailable — "
                     "falling back to status-name matching: %s", e)
        return out
    for col in (config.get("columnConfig") or {}).get("columns", []) or []:
        canonical = requested_lc.get((col.get("name") or "").strip().lower())
        if canonical is None:
            continue
        out[canonical] = {str(s.get("id")) for s in (col.get("statuses") or []) if s.get("id")}
    return out


def _issue_in_columns(issue: dict, columns: List[str], column_status_ids: dict) -> bool:
    """True if the issue's status belongs to any of the requested columns.

    By status ID when the column's id-set is populated (the accurate path);
    otherwise by case-insensitive status-name == column-name fallback.
    """
    status_field = ((issue or {}).get("fields") or {}).get("status") or {}
    status_id = str(status_field.get("id")) if status_field.get("id") else None
    status_name = (status_field.get("name") or "").strip().lower()
    for col in columns:
        ids = column_status_ids.get(col) or set()
        if ids:
            if status_id and status_id in ids:
                return True
        elif status_name and status_name == col.strip().lower():
            return True
    return False


def _fingerprint(fields: dict) -> str:
    """Stable hash over the fields whose change should trigger a regeneration."""
    payload = json.dumps(
        {k: fields[k] for k in
         ("summary", "assignee", "priority", "issuetype", "status", "fix_versions", "description")},
        sort_keys=True, ensure_ascii=False,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


# ── Sidecar state ───────────────────────────────────────────────────────────

def _load_state() -> dict:
    if _STATE_FILE.exists():
        try:
            return json.loads(_STATE_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as e:
            _log.warning("test_farm: state file unreadable (%s) — starting fresh", e)
    return {}


def _save_state(state: dict) -> None:
    _LOGS_DIR.mkdir(parents=True, exist_ok=True)
    _STATE_FILE.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")


# ── Claude Code (headless) ──────────────────────────────────────────────────

def _resolve_claude_bin(override: Optional[str] = None) -> str:
    """Locate the claude CLI, or raise with an actionable message."""
    if override:
        return override
    found = shutil.which("claude")
    if found:
        return found
    fallback = Path.home() / ".local" / "bin" / "claude.exe"
    if fallback.exists():
        return str(fallback)
    raise RuntimeError(
        "claude CLI not found on PATH. The test farm runs Claude Code headless "
        "against your Max subscription — install it and run `claude` once on this "
        "host (windows-work-all) to log in, or pass claude_bin=<path>."
    )


def _generate_gherkin_via_claude(fields: dict, *, claude_bin: str, model: str,
                                 max_thinking_tokens: Optional[int], timeout: int) -> str:
    """Invoke /generate-gherkin-scenarios headless; return the assistant text.

    The prompt is piped via stdin (not argv) so arbitrarily long descriptions
    can't blow the command-line length limit. ``cwd`` is the repo root so the
    project-scoped skill in ``.claude/skills/`` is discoverable. No tools are
    granted — the prompt forbids tool use and asks for text-only output, so the
    headless run never blocks on a permission prompt.
    """
    prompt = load_prompt("test_farm").format(
        key=fields["key"],
        summary=fields["summary"],
        issuetype=fields["issuetype"],
        priority=fields["priority"],
        status=fields["status"],
        fix_versions=", ".join(fields["fix_versions"]) or "-",
        description=fields["description"] or "(no description provided in the ticket)",
    )

    cmd = [claude_bin, "-p", "--model", model, "--output-format", "text"]
    env = None
    if max_thinking_tokens:
        env = {**os.environ, "MAX_THINKING_TOKENS": str(max_thinking_tokens)}

    _log.info("test_farm: generating scenarios for %s via claude (model=%s)", fields["key"], model)
    proc = subprocess.run(
        cmd, input=prompt, cwd=str(_REPO_ROOT),
        capture_output=True, text=True, timeout=timeout, env=env,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"claude exited {proc.returncode} for {fields['key']}: "
            f"{(proc.stderr or '').strip()[:500]}"
        )
    out = (proc.stdout or "").strip()
    if not out:
        raise RuntimeError(f"claude returned empty output for {fields['key']}")
    return out


# ── Markdown rendering ──────────────────────────────────────────────────────

def _slug(key: str) -> str:
    """GitHub-stable anchor slug for a ticket key (e.g. 'ICON-42' → 'icon-42')."""
    return re.sub(r"[^a-z0-9]+", "-", (key or "").lower()).strip("-")


def _cell(text: str) -> str:
    """Escape a value for a single markdown table cell."""
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _render_md(entries: List[dict], *, board_id, statuses, generated_at: str) -> str:
    """Render the full living document: header + summary nav table + sections."""
    out: List[str] = []
    out.append("# BDD Test Case Farm")
    out.append("")
    out.append(f"_Living document — auto-generated by `workflows/testing/tasks/test_farm.py`. "
               f"Last run: {generated_at}._")
    out.append("")
    out.append(f"Source: Jira board `{board_id}` · active sprint · "
               f"statuses {list(statuses)} · types {list(_INCLUDED_ISSUE_TYPES)} · "
               f"{len(entries)} ticket(s).")
    out.append("")

    # ── Summary nav table (fields per spec: Summary, FixVersion, Issue Type,
    #    Status, link to the ticket's test section) ────────────────────────────
    out.append("## Summary")
    out.append("")
    out.append("| Summary | FixVersion | Issue Type | Status | Tests |")
    out.append("|---------|------------|------------|--------|-------|")
    for e in entries:
        fv = ", ".join(e["fix_versions"]) or "-"
        out.append(f"| {_cell(e['summary'])} | {_cell(fv)} | {e['issuetype']} "
                   f"| {e['status']} | [{e['key']}](#{_slug(e['key'])}) |")
    out.append("")
    out.append("---")
    out.append("")

    # ── One section per ticket ────────────────────────────────────────────────
    for e in entries:
        out.append(f'<a id="{_slug(e["key"])}"></a>')
        out.append(f"## {e['key']} — {e['summary']}")
        out.append("")
        out.append("| Field | Value |")
        out.append("|-------|-------|")
        out.append(f"| Ticket Id | {e['key']} |")
        out.append(f"| Name | {_cell(e['summary'])} |")
        out.append(f"| Priority | {e['priority']} |")
        out.append(f"| Assignee | {_cell(e['assignee'])} |")
        out.append(f"| Issue Type | {e['issuetype']} |")
        out.append(f"| Status | {e['status']} |")
        out.append(f"| Fix Version(s) | {_cell(', '.join(e['fix_versions']) or '-')} |")
        out.append(f"| Last generated | {e['generated_at']} |")
        out.append("")
        out.append(e["gherkin"])
        out.append("")
        out.append("---")
        out.append("")

    return "\n".join(out) + "\n"


# ── Task ──────────────────────────────────────────────────────────────────────

@log_result()
@SPROUT.task()
def run_test_farm(board_id: int, **kwargs):
    """Generate / refresh BDD Gherkin scenarios for active-sprint Bug/Story tickets.

    Tickets are processed strictly one at a time: take the next ticket's data,
    run the /generate-gherkin-scenarios skill against it, append the result to
    the living document, pause (rate limit), repeat. The whole markdown file is
    rewritten after every ticket so the top summary table stays in sync and an
    interrupted run still leaves every completed ticket on disk.

    Args:
        board_id: Jira Software board id (`rapidView=<id>` in the board URL) —
                  the same board workflows/hud/tasks/hud_jira reads.

    Kwargs:
        cfg_id__jira:        Config key for Jira (default 'JIRA').
        statuses:            Status names to include (default DEFAULT_STATUSES).
        claude_model:        Model alias for `claude --model` (default 'sonnet').
        claude_bin:          Explicit path to the claude CLI (default: PATH lookup).
        max_thinking_tokens: If set, exported as MAX_THINKING_TOKENS for each run.
        per_ticket_timeout:  Seconds allowed per claude invocation (default 420).
        inter_ticket_delay:  Seconds to pause between consecutive Claude
                             generations, for rate limiting (default 5). Skipped
                             on cache reuses and after the final ticket.
        max_results:         Board fetch cap (default 200).
        limit:               Max NEW generations this run (default None = no cap).
                             Deferred tickets show a "pending" placeholder and
                             regenerate on a later run — lets the initial backlog
                             spread across several daily runs / bounds quota use.
        force:               If True, regenerate every ticket, ignoring the cache.

    Returns:
        Summary string: detected / generated / reused / failed counts + md path.
    """
    cfg_id__jira = kwargs.get("cfg_id__jira", APP_NAME_JIRA)
    statuses = kwargs.get("statuses") or DEFAULT_STATUSES
    claude_model = kwargs.get("claude_model", _DEFAULT_CLAUDE_MODEL)
    claude_bin = _resolve_claude_bin(kwargs.get("claude_bin"))
    max_thinking_tokens = kwargs.get("max_thinking_tokens")
    per_ticket_timeout = int(kwargs.get("per_ticket_timeout", _DEFAULT_PER_TICKET_TIMEOUT))
    inter_ticket_delay = int(kwargs.get("inter_ticket_delay", _DEFAULT_INTER_TICKET_DELAY))
    max_results = int(kwargs.get("max_results", _MAX_BOARD_ISSUES))
    force = bool(kwargs.get("force", False))
    _limit = kwargs.get("limit")
    limit = int(_limit) if _limit is not None else None  # max NEW generations this run

    cfg__jira = CONFIG_MANAGER.get(cfg_id__jira)
    api_boards = ApiServiceJiraBoards(cfg__jira)

    # Reuse the HUD's sprint scope; filter issue type server-side (Bug/Story
    # are real type names). Status is filtered client-side by *column membership*
    # because the focus statuses are board column names, not status names.
    type_clause = ", ".join(_INCLUDED_ISSUE_TYPES)
    jql = f'{_SPRINT_FILTER_JQL} AND issuetype in ({type_clause}) ORDER BY updated DESC'

    _log.info("test_farm: fetching board %s — jql: %s", board_id, jql)
    response = api_boards.get_board_issues(
        board_id=board_id, jql=jql, fields=_FETCH_FIELDS, max_results=max_results,
    )
    issues = (response or {}).get("issues", []) or []

    # Bucket by board column (In Review / In Progress / Ready / In Analysis) the
    # same way hud_jira does — match underlying status IDs, not column labels.
    column_status_ids = _resolve_column_status_ids(api_boards, board_id, statuses)
    issues = [i for i in issues if _issue_in_columns(i, statuses, column_status_ids)]
    _log.info("test_farm: %d Bug/Story ticket(s) in focus columns on board %s",
              len(issues), board_id)

    state = _load_state()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    candidates = [f for f in (_extract_fields(i) for i in issues) if f["key"]]
    total = len(candidates)
    generated = reused = failed = deferred = 0

    def _flush() -> None:
        """Re-render the living document from the current entry state."""
        md = _render_md(entries, board_id=board_id, statuses=statuses, generated_at=now)
        _LOGS_DIR.mkdir(parents=True, exist_ok=True)
        _FARM_MD.write_text(md, encoding="utf-8")

    # Pre-seed every detected ticket with a placeholder so the document shows the
    # full summary table + all sections immediately; each section is then filled
    # in as its ticket is processed (the file is never blank during a slow run).
    entries: List[dict] = [
        {**f, "gherkin": "> _Queued — scenarios will appear here once generated._",
         "generated_at": "—"}
        for f in candidates
    ]
    _flush()

    # ── One ticket at a time: take the next ticket's data → run the skill →
    #    append to the document → pause (rate limit) → repeat. ──────────────────
    for idx, fields in enumerate(candidates):
        key = fields["key"]
        fp = _fingerprint(fields)
        prior = state.get(key) or {}
        unchanged = (not force) and prior.get("fingerprint") == fp and prior.get("gherkin")
        called_claude = False

        if unchanged:
            gherkin = prior["gherkin"]
            gen_at = prior.get("generated_at", now)
            reused += 1
            _log.info("test_farm: [%d/%d] %s unchanged — reusing scenarios", idx + 1, total, key)
        elif limit is not None and generated >= limit:
            # Per-run generation budget reached: defer this ticket. Show prior
            # scenarios if we have them, else a placeholder. Don't touch state,
            # so it regenerates on a later run.
            deferred += 1
            gherkin = prior.get("gherkin") or \
                "> _Pending — deferred to a later run (per-run generation limit reached)._"
            gen_at = prior.get("generated_at", "—")
            _log.info("test_farm: [%d/%d] %s — deferred (limit %d reached)", idx + 1, total, key, limit)
        else:
            called_claude = True
            _log.info("test_farm: [%d/%d] %s — generating scenarios", idx + 1, total, key)
            try:
                gherkin = _generate_gherkin_via_claude(
                    fields, claude_bin=claude_bin, model=claude_model,
                    max_thinking_tokens=max_thinking_tokens, timeout=per_ticket_timeout,
                )
            except Exception as e:
                # Don't fail the whole batch on one ticket. Keep prior scenarios
                # if we have them (and leave the old fingerprint so it retries
                # next run); otherwise drop a visible placeholder.
                _log.error("test_farm: generation failed for %s: %s", key, e)
                failed += 1
                if prior.get("gherkin"):
                    gherkin = prior["gherkin"]
                    gen_at = prior.get("generated_at", now)
                else:
                    gherkin = f"> _Scenario generation failed on {now}: {e}_"
                    gen_at = now
            else:
                gen_at = now
                generated += 1
                state[key] = {
                    "fingerprint": fp,
                    "generated_at": gen_at,
                    "fields": {k: fields[k] for k in
                               ("summary", "assignee", "priority", "issuetype", "status", "fix_versions")},
                    "gherkin": gherkin,
                }
                _save_state(state)   # persist the cache as we go — resumable

        entries[idx] = {**fields, "gherkin": gherkin, "generated_at": gen_at}
        _flush()                     # update this ticket's section in the document now

        # Rate limit: pause only after a real Claude call, never after the last.
        if called_claude and idx < total - 1 and inter_ticket_delay > 0:
            _log.info("test_farm: rate-limit pause %ds before next ticket", inter_ticket_delay)
            time.sleep(inter_ticket_delay)

    _save_state(state)
    summary = (f"BDD farm: {total} ticket(s) — {generated} generated, "
               f"{reused} reused, {deferred} deferred, {failed} failed → {_FARM_MD}")
    _log.info(summary)
    return summary
