name: HARQIS-WORK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Git Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build --no-cache -t harqis-work .

    - name: Run Tests
      run: docker run harqis-work
      env:
        ENV_ROOT_DIRECTORY: /app